# Generated by Django 3.1 on 2023-09-08 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Project name', max_length=50)),
                ('category', models.CharField(help_text='Project category', max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='Project start date')),
                ('deadline', models.DateTimeField(help_text='Project deadline')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Task', max_length=50)),
                ('status', models.BooleanField(default=False, help_text='Task done?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectp.project')),
            ],
        ),
    ]
