# Generated by Django 3.1 on 2023-09-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(help_text='Project deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now_add=True, help_text='Project start date'),
        ),
    ]
